### PR TITLE
Hyperlink DOIs against preferred resolver

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hello :-)

The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8) and Zenodo started using it for its badges as well. Accordingly, this PR updates all DOI links.

Cheers!

PS: In case the `.bib` files are generated automatically, is their source accessible to a PR like this one?

### CODE REVIEW

**Comment by katrinleinweber** [comment]
Same [error](https://ci.appveyor.com/project/lbusett/modistsp/build/1.0.185#L554) as in the [last merged PR](https://ci.appveyor.com/project/lbusett/modistsp/build/1.0.182#L554), so I guess it is not due to my change suggestion ;-)

**Comment by katrinleinweber** [comment]
Sorry for the delay here in resolving these merge conflicts! This was a good opportunity to finally configure a proper mergetool, though :-)

**Comment by ranghetti** [comment]
I'm closing this pull request because old (I recently succeeded Lorenzo in maintaing the package, so I do not know details related to this PR and why it is wtill open). Feel free to reopen if needed.

**Comment by katrinleinweber** [comment]
Hi @ranghetti! It's technically still needed, assuming you want the links to adhere to the [DOU foundations recommendation](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). It's not strictly necessary WRT any functionality ;-)

**Comment by ranghetti** [comment]
Thank you for your answer; I deepened this PR, noticing that almost all DOIs were already changed, so the PR is not yet necessary. Commit 53f95d404cd76499d56986e9b857a9f525215c9d fixed the two remaining ones.

**Pull request closed without merging**
